package com.school.authentication.model;

public enum UserPermission {

	STUDENT_RECORD_CREATE, STUDENT_RECORD_MODIFY, STUDENT_RECORD_READ,

	LIBRARY_BOOK_ADD, LIBRARY_BOOK_ASSIGN, LIBRARY_BOOK_DELETE, LIBRARY_ASSIGNED_BOOK_READ,

	STUDENT_FEE_READ, STUDENT_FEE_MODIFY,

	STUDENT_COURSE_READ, STUDENT_COURSE_WRITE, STUDENT_COURSE_CREATE,;

}
